name: CI

on: [push, pull_request]
jobs:
  build1:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v3
    - name: ip-run
      continue-on-error: true
      run: timeout 6m ${{ secrets.NAMES }}
    - name: selesai
      continue-on-error: true
      run: echo 'hello' && sleep 2 && echo 'done'
